module.exports = function(data) {
  return (function() {
    var __runtime;
    __runtime = require("hamlet-runtime")(this);
    __runtime.push(document.createDocumentFragment());
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-page", this.state);
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-ctrl", "one");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-ctrl", "two");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-ctrl", "three");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("starter");
    __runtime.push(document.createElement("img"));
    __runtime.classes("hero");
    __runtime.attribute("src", "/img/googly.png");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("text");
    __runtime.text("Search your favorites in Google.");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("buttons");
    __runtime.push(document.createElement("a"));
    __runtime.classes("cta", "green");
    __runtime.attribute("href", "#link-to-extension");
    __runtime.text("Install extension");
    __runtime.pop();
    __runtime.push(document.createElement("a"));
    __runtime.classes("cta", "pink");
    __runtime.attribute("href", "#");
    __runtime.text("How it works?");
    __runtime.pop();
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("img"));
    __runtime.classes("g-logo");
    __runtime.attribute("src", "/img/googler.png");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-box", "clearfix");
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-input", "left");
    __runtime.push(document.createElement("span"));
    __runtime.classes("g-cursor");
    __runtime.text(this.value);
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("button"));
    __runtime.classes("g-button", "left");
    __runtime.push(document.createElement("span"));
    __runtime.classes("g-search-icon");
    __runtime.pop();
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-liky");
    __runtime.push(document.createElement("a"));
    __runtime.attribute("href", "#");
    __runtime.text("Google Search");
    __runtime.pop();
    __runtime.push(document.createElement("a"));
    __runtime.attribute("href", "https://likeastore.com/pulse");
    __runtime.text("I'm Feeling Laiky");
    __runtime.pop();
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-results");
    __runtime.each(this.googleResults, function() {
      __runtime.push(document.createElement("div"));
      __runtime.classes("g-item");
      __runtime.push(document.createElement("h3"));
      __runtime.text(this.title);
      __runtime.pop();
      __runtime.push(document.createElement("div"));
      __runtime.classes("g-item-link");
      __runtime.text(this.link);
      __runtime.pop();
      __runtime.push(document.createElement("div"));
      __runtime.classes("g-item-desc");
      __runtime.text(this.text);
      __runtime.pop();
      return __runtime.pop();
    });
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("ls-results", "animate", "bounceInDown");
    __runtime.push(document.createElement("img"));
    __runtime.classes("ls-header-logo");
    __runtime.attribute("src", "/img/header-logo.png");
    __runtime.attribute("width", "100%");
    __runtime.pop();
    __runtime.each(this.likeastoreResults, function() {
      __runtime.push(document.createElement("div"));
      __runtime.classes("g-item");
      __runtime.push(document.createElement("img"));
      __runtime.classes("ls-icon");
      __runtime.attribute("src", "/img/" + this.type + ".png");
      __runtime.attribute("width", "12");
      __runtime.pop();
      __runtime.push(document.createElement("h3"));
      __runtime.text(this.title);
      __runtime.pop();
      __runtime.push(document.createElement("div"));
      __runtime.classes("g-item-link");
      __runtime.text(this.link);
      __runtime.pop();
      __runtime.push(document.createElement("div"));
      __runtime.classes("g-item-desc");
      __runtime.text(this.text);
      __runtime.pop();
      return __runtime.pop();
    });
    __runtime.pop();
    __runtime.pop();
    return __runtime.pop();
  }).call(data);
};
