module.exports = function(data) {
  return (function() {
    var __runtime;
    __runtime = require("hamlet-runtime")(this);
    __runtime.push(document.createDocumentFragment());
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-page");
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-ctrl", "one");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-ctrl", "two");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("g-ctrl", "three");
    __runtime.pop();
    __runtime.push(document.createElement("img"));
    __runtime.classes("g-logo");
    __runtime.attribute("src", "/img/googler.png");
    __runtime.pop();
    __runtime.push(document.createElement("div"));
    __runtime.classes("center", "clearfix");
    __runtime.push(document.createElement("input"));
    __runtime.classes("g-input", "left");
    __runtime.attribute("type", "text");
    __runtime.attribute("value", this.value);
    __runtime.pop();
    __runtime.push(document.createElement("button"));
    __runtime.classes("g-button", "left");
    __runtime.push(document.createElement("span"));
    __runtime.classes("g-search-icon");
    __runtime.pop();
    __runtime.pop();
    __runtime.pop();
    __runtime.pop();
    return __runtime.pop();
  }).call(data);
};
